title: Krishanu Kumar # your name (or website title) here
logo: "" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Researcher at TAU
  <br><br>
  fluid mechanics | wind wave and water current interaction | wave breaking | multiphase flows | experimental methods
  <br><br>
  <a href="./">Research</a>
  <br>
  <a href="./about_me">About Me</a>
  <br>
  <a href="./code">Code</a>
  <br><br>
  <a href="https://scholar.google.com/citations?user=l9c73IQAAAAJ&hl=en">Google Scholar</a> | <a href="https://www.linkedin.com/in/krishanu-kumar-973814105/">LinkedIn</a> |
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
#github:
#  is_project_page: false
